# SciSynth — Complete Usage Guide

> All inputs go into the **chat box** at the bottom of the Chainlit UI (`http://127.0.0.1:7860`)

---

## Mode 1: ⚡ Quick Q&A

**What it does:** You ask a question → SciSynth searches the ingested papers → LLM answers with `[chunk_id]` citations.

**How to use:** Just type a question directly (no prefix).

### Input Examples
```
What improves retrieval quality in long-document QA?
```
```
How does claim verification work in scientific papers?
```
```
What is multi-hop retrieval?
```

### Expected Output
```markdown
## Answer

Long-document question answering requires chunk-level retrieval before
synthesis [paper_qasper_demo:chunk-0]. Models need to gather evidence from
multiple sections instead of relying on a single passage. Retrieval quality
strongly affects downstream generation...

---
### 📖 Citations
- [paper_qasper_demo:chunk-0] Question Answering over Long Documents · score 0.51
  > QASPER-style long-document QA Long-document question answering requires...

---
Model: llama-3.1-8b-instant · Retrieval hops: 1
```

> [!NOTE]
> Quick Q&A only searches the **ingested index** (currently 2 demo papers about QASPER-style QA and SciFact verification). So questions must relate to those topics to get meaningful answers.

---

## Mode 2: 🔬 Deep Research (arXiv) — **THE MAIN FEATURE**

**What it does:** You give a research topic → 5 AI agents collaborate to produce a full research report:
1. **Planner** breaks the topic into 3–5 sections
2. **Researcher** searches arXiv, downloads PDFs, retrieves evidence per section
3. **Writer** drafts each section with citations
4. **Reviewer** checks quality — if citations are missing or content is weak, it sends the section back to Researcher or Writer
5. **Synthesizer** merges all sections into a cohesive report with intro + conclusion

**How to use:** Type `/research` followed by your topic.

### Input Examples
```
/research How do transformer models improve scientific document question answering?
```
```
/research Retrieval augmented generation techniques for knowledge-intensive NLP tasks
```
```
/research Neural approaches to automatic scientific paper summarization
```
```
/research The role of attention mechanisms in long-context language models
```

### Expected Output (step-by-step in the chat)

**Step 1 — Header appears:**
```
## 🔬 Deep Research: How do transformer models improve scientific document QA?
Evidence source: 🌐 arXiv (live papers)
Starting multi-agent pipeline...
Agents: Planner → Researcher → Writer → Reviewer ↺ → Synthesizer
```

**Step 2 — Progress steps appear one by one:**
```
📋 Planning
Created 5 sections:
  1. Transformer Architectures for Document Understanding
  2. Retrieval-Augmented Generation in QA Systems
  3. Long-Context Handling Strategies
  4. Evidence Extraction and Citation Methods
  5. Evaluation Benchmarks and Datasets

🔍 Researching
Retrieved 8 evidence chunks for section 1

✍️ Writing
Drafted section 1 (1240 chars)

🔎 Reviewing
Section 1: accept — Well-cited and addresses the topic

➡️ Next Section
Moving to section 2

🔍 Researching
Retrieved 6 evidence chunks for section 2
...
(repeats for all sections)
...

🧬 Synthesizing
Merging sections into a cohesive report...
```

**Step 3 — Final report appears:**
```markdown
# 📄 Research Report: How do transformer models improve scientific document QA?

## Introduction
Transformer-based models have revolutionized scientific document question
answering by enabling multi-hop reasoning across long texts...

## Transformer Architectures for Document Understanding
Recent work has shown that pre-trained transformer models such as SciBERT
and Longformer can effectively encode scientific documents [arxiv_2103.xxxxx:chunk-0]...

## Retrieval-Augmented Generation in QA Systems
RAG combines retrieval with generation to ground answers in evidence
[arxiv_2005.11401:chunk-2]...

(... more sections ...)

## Conclusion
This survey highlights several key findings: (1) transformer architectures
with sparse attention are most effective for long documents...

---
## 📚 Evidence Sources
- Longformer: The Long-Document Transformer
- Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
- ...

Generated by SciSynth Deep Research · llama-3.1-8b-instant · 45.2s · 5 sections
```

> [!IMPORTANT]
> This mode fetches **real papers from arXiv live**. It takes 30–60 seconds because it makes multiple arXiv API calls + PDF downloads + several LLM calls. This is the most powerful mode and requires no pre-ingested data. Internet connection required.

---

## Mode 3: 📚 Deep Research (Index)

**What it does:** Same multi-agent pipeline as above, but only searches the **ingested local papers** instead of arXiv.

**How to use:** Type `/research-index` followed by your topic.

### Input Examples
```
/research-index Chunk-level retrieval strategies for document QA
```
```
/research-index Evidence verification in scientific claims
```

### Expected Output
Same format as Mode 2, but cites ingested papers only (currently `paper_qasper_demo` and `paper_scifact_demo`).

> [!WARNING]
> Since the index only has 2 tiny demo papers, this mode will produce thin results right now. To make it useful, ingest more papers first with `scisynth ingest`.

---

## Mode 4: 📄 arXiv Single Paper Q&A

**What it does:** You give an arXiv paper URL/ID + a question → SciSynth fetches that specific paper, extracts its PDF text, chunks it, and answers your question from it.

**How to use:** Type `/arxiv <paper_url_or_id> <your question>`

### Input Examples
```
/arxiv 2005.11401 How does retrieval augmented generation work?
```
```
/arxiv https://arxiv.org/abs/1706.03762 What is the attention mechanism and how does it work?
```
```
/arxiv 2304.08485 What are the main contributions of this paper?
```

### Expected Output
```markdown
## Answer

Retrieval-Augmented Generation (RAG) combines a pre-trained retriever with
a seq2seq generator [arxiv_2005.11401:chunk-3]. The retriever uses Dense
Passage Retrieval to fetch relevant documents from a knowledge source, which
are then concatenated with the input and passed to the generator
[arxiv_2005.11401:chunk-5]...

---
### 📖 Citations
- [arxiv_2005.11401:chunk-3] Retrieval-Augmented Generation... · score 0.89
  > We propose RAG models that combine pre-trained parametric...
- [arxiv_2005.11401:chunk-5] Retrieval-Augmented Generation... · score 0.72
  > The retriever component uses DPR to index Wikipedia passages...

---
Model: llama-3.1-8b-instant · Retrieval hops: 1
```

> [!TIP]
> This is great for **drilling into one specific paper**. You can find arXiv IDs from [arxiv.org](https://arxiv.org). Just grab the number from the URL (e.g. `2005.11401` from `https://arxiv.org/abs/2005.11401`).

---

## Mode 5: 🌐 arXiv Discovery

**What it does:** You ask a question → SciSynth keyword-searches arXiv → fetches the top 5 matching papers → answers your question using evidence from all of them.

**How to use:** Type `/discover` followed by your question.

### Input Examples
```
/discover What are recent advances in retrieval augmented generation?
```
```
/discover How do language models handle scientific reasoning?
```
```
/discover Neural methods for automatic citation recommendation
```

### Expected Output
```markdown
## Answer

Recent work on retrieval augmented generation has focused on several fronts.
RAG [arxiv_2005.11401:chunk-0] proposed combining retrieval with generation...
Meanwhile, REALM [arxiv_2002.08909:chunk-1] introduced retrieval-augmented
pre-training... FiD [arxiv_2007.01282:chunk-0] showed that fusing evidence
from multiple passages improves answer quality...

---
### 📖 Citations
- [arxiv_2005.11401:chunk-0] Retrieval-Augmented Generation... · score 0.91
- [arxiv_2002.08909:chunk-1] REALM: Retrieval-Augmented Language Model... · score 0.78
- [arxiv_2007.01282:chunk-0] Leveraging Passage Retrieval... · score 0.65

---
Model: llama-3.1-8b-instant · Retrieval hops: 1
```

> [!TIP]
> This is like a quick multi-paper Q&A. For a **full structured report**, use `/research` instead.

---

## Quick Reference

| Mode | Command | Source | Speed | Best For |
|------|---------|--------|-------|----------|
| Quick Q&A | `<question>` | Ingested index | ~3s | Fast Q&A on ingested papers |
| Deep Research (arXiv) | `/research <topic>` | Live arXiv | ~30-60s | **Full research reports** |
| Deep Research (Index) | `/research-index <topic>` | Ingested index | ~15-30s | Reports from your own corpus |
| arXiv Paper Q&A | `/arxiv <id> <question>` | One arXiv paper | ~5-10s | Deep-dive into a specific paper |
| arXiv Discovery | `/discover <question>` | arXiv search | ~10-15s | Quick multi-paper answers |

---

## What You Should Try Right Now

**Best first demo (works immediately, no setup needed):**

````
/research How do large language models handle long-context scientific document understanding?
````

This will:
1. Plan 5 research sections
2. Search arXiv for real papers on this topic
3. Download and read those papers
4. Write and review each section
5. Produce a full research report with citations

**Expect it to take ~30-60 seconds.** You'll see each agent step appear in the chat as it progresses.
